In [1]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [2]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import math as mt
import warnings

# 한글출력
matplotlib.rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False
warnings.filterwarnings(action='ignore') 

from src import crs, PublicPredictor
from src.dbc import utils, TimeDivisionKMeans

In [3]:
# 1. load_excel
data_path = "data/apt_1.xlsx"
xlsx = pd.read_excel(data_path, header=None,
                     skiprows=2, engine="openpyxl")

# 2. data preprocessing
p, m = crs.utils.data_preprocessing(xlsx)

m.set_index("month", inplace=True)

# 3. data init
_month = 1

month_df = pd.DataFrame(m.loc[_month])
month_df.reset_index(inplace=True)

month_df.columns = ['name', 'usage (kWh)']

PUBLIC_PERCENTAGE = 30
APT = crs.utils.get_APT(month_df, PUBLIC_PERCENTAGE)

calc = crs.models.ManagementOffice(
        month=_month,
        households=month_df,
        APT=APT,
        contract="단일계약"
    )
apt = calc.apart

In [98]:
m_15 = utils.data_preprocessing(xlsx)

df = utils.dimension_reduction(m_15)
m_60 = df.copy()

m_60.head()

m_60_1 = m_60[m_60.index.month == 1].copy()
m_60_1.head()

아파트1-104-1206  아파트1-104-303  아파트1-104-1307  \
2019-01-01 00:00:00          0.033         0.000          0.034   
2019-01-01 01:00:00          0.048         0.000          0.033   
2019-01-01 02:00:00          0.032         0.000          0.039   
2019-01-01 03:00:00          0.033         0.000          0.039   
2019-01-01 04:00:00          0.032         0.001          0.033   

                     아파트1-104-1208  아파트1-104-408  아파트1-104-203  아파트1-103-1402  \
2019-01-01 00:00:00          0.037         0.062         0.322          0.240   
2019-01-01 01:00:00          0.037         0.063         0.185          0.257   
2019-01-01 02:00:00          0.036         0.062         0.175          0.384   
2019-01-01 03:00:00          0.037         0.062         0.167          0.276   
2019-01-01 04:00:00          0.037         0.063         0.197          0.266   

                     아파트1-103-402  아파트1-103-1201  아파트1-103-801  ...  \
2019-01-01 00:00:00         0.295          0.373         0.243  ...   
2019-01-01 01:00:00         0.397          0.257         0.228  ...   
2019-01-01 02:00:00         0.353          0.123         0.141  ...   
2019-01-01 03:00:00         0.488          0.142         0.159  ...   
2019-01-01 04:00:00         0.278          0.190         0.227  ...   

                     아파트1-102-901  아파트1-103-1905  아파트1-103-503  아파트1-103-1504  \
2019-01-01 00:00:00         0.534          0.188         0.400          0.318   
2019-01-01 01:00:00         0.396          0.434         0.355          0.250   
2019-01-01 02:00:00         0.194          0.337         0.379          0.274   
2019-01-01 03:00:00         0.286          0.263         0.375          0.264   
2019-01-01 04:00:00         0.275          0.245         0.310          0.423   

                     아파트1-103-606  아파트1-103-903  아파트1-103-1106  아파트1-103-705  \
2019-01-01 00:00:00         0.420         0.626          0.484         0.289   
2019-01-01 01:00:00         0.465         0.409          0.459         0.336   
2019-01-01 02:00:00         0.326         0.307          0.405         0.382   
2019-01-01 03:00:00         0.336         0.345          0.298         0.291   
2019-01-01 04:00:00         0.360         0.364          0.212         0.347   

                     아파트1-103-1505  아파트1-103-406  
2019-01-01 00:00:00          0.305         0.652  
2019-01-01 01:00:00          0.332         0.557  
2019-01-01 02:00:00          0.311         0.491  
2019-01-01 03:00:00          0.261         0.511  
2019-01-01 04:00:00          0.294         0.507  

[5 rows x 108 columns]

In [99]:
from src import TimeDivisionKMeans

tdKMeans = TimeDivisionKMeans(datas=m_60_1)
tdKMeans.fit()

tdKMeans.cluster_info.head()[
    tdKMeans.cluster_info.columns[:10]
]

1/248 - ECV:85%
11/248 - ECV:79%
21/248 - ECV:86%
31/248 - ECV:86%
41/248 - ECV:87%
51/248 - ECV:83%
61/248 - ECV:88%
71/248 - ECV:83%
81/248 - ECV:87%
91/248 - ECV:83%
101/248 - ECV:85%
111/248 - ECV:80%
121/248 - ECV:86%
131/248 - ECV:78%
141/248 - ECV:85%
151/248 - ECV:86%
161/248 - ECV:86%
171/248 - ECV:77%
181/248 - ECV:81%
191/248 - ECV:83%
201/248 - ECV:85%
211/248 - ECV:81%
221/248 - ECV:83%
231/248 - ECV:79%
241/248 - ECV:87%
248/248 - ECV:84%


아파트1-104-1206 아파트1-104-303 아파트1-104-1307 아파트1-104-1208  \
division_round                                                          
0                          0            0             0             0   
1                          0            0             0             0   
2                          0            0             0             0   
3                          0            0             0             0   
4                          0            0             0             0   

               아파트1-104-408 아파트1-104-203 아파트1-103-1402 아파트1-103-402  \
division_round                                                        
0                         0            0             1            1   
1                         0            1             1            3   
2                         0            0             0            0   
3                         0            0             0            0   
4                         0            0             0            2   

               아파트1-103-1201 아파트1-103-801  
division_round                             
0                          1            0  
1                          1            1  
2                          0            0  
3                          0            0  
4                          2            0

# 최종 기여도그룹 부여 ( 1.라벨 )

In [196]:
labels_ = np.array([])

for col in tdKMeans.cluster_info.columns:
#     max_group = tdKMeans.cluster_info[col].value_counts().idxmax()
    max_group = tdKMeans.cluster_info[col].mean().round().astype("int")
    
    labels_ = np.append(labels_,max_group)
    
labels_.astype("int")

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 2, 2, 4, 1, 2, 1, 1, 3, 0,
       1, 2, 1, 1, 0, 2, 2, 1, 2, 1, 1, 1, 1, 3, 2, 1, 3, 1, 1, 1, 1, 2,
       1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 0, 1, 2, 2, 2, 1, 3, 2, 2, 2,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 1, 1, 3, 3, 1, 1, 3, 2, 3, 2,
       2, 3, 2, 1, 2, 2, 4, 1, 2, 2, 1, 2, 2, 2, 3, 1, 1, 1, 2, 2])

# 최종 기여도그룹 번호 부여

In [197]:
_unique_labels = np.unique(tdKMeans.labels_)
groups_ = np.zeros(len(labels_)) - 1

for idx, label in enumerate(_unique_labels):
    groups_[labels_ == label] = idx
    
groups_

array([0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 2., 1., 2., 2., 4., 1.,
       2., 1., 1., 3., 0., 1., 2., 1., 1., 0., 2., 2., 1., 2., 1., 1., 1.,
       1., 3., 2., 1., 3., 1., 1., 1., 1., 2., 1., 1., 2., 1., 2., 1., 1.,
       2., 2., 1., 2., 1., 0., 1., 2., 2., 2., 1., 3., 2., 2., 2., 1., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 1., 2., 1., 1., 3., 3., 1., 1., 3.,
       2., 3., 2., 2., 3., 2., 1., 2., 2., 4., 1., 2., 2., 1., 2., 2., 2.,
       3., 1., 1., 1., 2., 2.])

# 최종 클러스터링 패턴 선정

In [198]:
# 0번 그룹 친구들
group_df = tdKMeans.cluster_info.iloc[:,tdKMeans.groups_ == 0]

In [204]:
_unique_groups = np.unique(groups_)

In [205]:
clusters_ = np.array([])

for _group in _unique_groups:
    group_df = tdKMeans.cluster_info.iloc[:,tdKMeans.groups_ == _group]

    for _round in range(len(tdKMeans.kmeans_)):
        max_cluster = group_df.iloc[_round].value_counts().idxmax()

        clusters_ = np.append(
            clusters_,
            tdKMeans.kmeans_[_round].clusters_[max_cluster]
        )

print(clusters_.shape)
clusters_[:5]

(3720,)


array([0.18205 , 0.1265  , 0.1197  , 0.236275, 0.226675])

In [206]:
clusters_ = clusters_.reshape(len(_unique_groups), -1)
clusters_

array([[0.18205   , 0.1265    , 0.1197    , ..., 0.2248125 , 0.21275   ,
        0.20725   ],
       [0.25958824, 0.30376471, 0.29570588, ..., 0.49497959, 0.4767551 ,
        0.42371429],
       [0.4812    , 0.38563333, 0.3142    , ..., 0.49497959, 0.4767551 ,
        0.42371429],
       [0.72392308, 0.66823077, 0.57923077, ..., 0.70086364, 0.83281818,
        0.73222727],
       [0.72392308, 0.66823077, 0.57923077, ..., 0.70086364, 0.83281818,
        0.73222727]])

In [207]:
cluster_df = pd.DataFrame(clusters_.T, index=m_60_1.index)

cluster_df

0         1         2         3         4
2019-01-01 00:00:00  0.182050  0.259588  0.481200  0.723923  0.723923
2019-01-01 01:00:00  0.126500  0.303765  0.385633  0.668231  0.668231
2019-01-01 02:00:00  0.119700  0.295706  0.314200  0.579231  0.579231
2019-01-01 03:00:00  0.236275  0.369968  0.523083  0.593571  0.523083
2019-01-01 04:00:00  0.226675  0.363258  0.487167  0.637286  0.487167
...                       ...       ...       ...       ...       ...
2019-01-31 19:00:00  0.184000  0.413326  0.678091  0.770167  0.914333
2019-01-31 20:00:00  0.189348  0.407605  0.608727  0.716583  1.101000
2019-01-31 21:00:00  0.224813  0.494980  0.494980  0.700864  0.700864
2019-01-31 22:00:00  0.212750  0.476755  0.476755  0.832818  0.832818
2019-01-31 23:00:00  0.207250  0.423714  0.423714  0.732227  0.732227

[744 rows x 5 columns]

In [208]:
cluster_df.sum()

0    135.225968
1    267.551466
2    379.955669
3    424.176721
4    448.757091
dtype: float64

In [209]:
group_df = pd.DataFrame()

group_df['가구명'] = m_60_1.columns
group_df['usage (kWh)'] = m_60_1.sum().round().values.astype("int")
group_df['label'] = tdKMeans.groups_

group_df.head()

가구명  usage (kWh)  label
0  아파트1-104-1206           99      0
1   아파트1-104-303           10      0
2  아파트1-104-1307           23      0
3  아파트1-104-1208           40      0
4   아파트1-104-408           39      0

In [210]:
group_df[5:10]

가구명  usage (kWh)  label
5   아파트1-104-203          197      1
6  아파트1-103-1402          218      0
7   아파트1-103-402          228      1
8  아파트1-103-1201           84      0
9   아파트1-103-801          223      0

In [238]:
uid = '아파트1-103-1201'

In [235]:
weight = (_unique_labels + 1) / _unique_labels.sum()
weight

array([0.04761905, 0.0952381 , 0.14285714, 0.19047619, 0.23809524,
       0.28571429, 0.33333333])

In [219]:
weight = tdKMeans.cluster_info[uid] / tdKMeans.cluster_info[uid].sum()
weight

division_round
0           0.0
1      0.005051
2           0.0
3           0.0
4           0.0
         ...   
243         0.0
244         0.0
245    0.010101
246    0.005051
247         0.0
Name: 아파트1-103-801, Length: 248, dtype: object

In [239]:
weight_mean = pd.DataFrame()

weight_mean['label'] = (tdKMeans.cluster_info[uid]).copy()
weight_mean['weight'] = weight_mean['label'].map(lambda x: weight[x])

weight_mean['weight mean'] = (weight_mean['label'] + 1) * weight_mean['weight']

weight_sum = weight_mean['weight'].sum()
weight_sum_total = weight_mean['weight mean'].sum()

weight_sum_total / weight_sum - 1

0.6158940397350963

In [214]:
tdKMeans.cluster_info['아파트1-104-203'].value_counts()

1    124
0    117
2      6
3      1
Name: 아파트1-104-203, dtype: int64

In [215]:
min_anomaly_data = pd.DataFrame()

for label in _unique_groups:
    now_step_df = group_df[group_df['label'] == label]
    next_step_min = group_df[group_df['label'] == (label + 1)]['usage (kWh)'].min()
    chk_idx = now_step_df['usage (kWh)'] > next_step_min\
    
    chk = now_step_df[chk_idx]
    
    if len(chk) != 0:
        min_anomaly_data = min_anomaly_data.append(
            chk
        )
    
min_anomaly_data

가구명  usage (kWh)  label
6   아파트1-103-1402          218      0
9    아파트1-103-801          223      0
32  아파트1-101-1502          219      0
39  아파트1-102-1501          262      0
42   아파트1-102-401          237      0
44   아파트1-102-801          280      0
49   아파트1-103-803          222      0
57  아파트1-103-1804          214      0
79  아파트1-103-1302          203      0
98   아파트1-102-901          202      0
13  아파트1-103-1502          397      1
30  아파트1-101-1403          380      1
43   아파트1-102-802          406      1
46  아파트1-103-1805          386      1
51  아파트1-103-1903          405      1
60  아파트1-103-1706          381      1
63   아파트1-103-305          371      1
65   아파트1-103-203          371      1
89   아파트1-101-503          422      1
90   아파트1-101-404          386      1
92  아파트1-101-1504          389      1
96  아파트1-102-1201          387      1
97   아파트1-102-501          387      1
35   아파트1-101-704          473      2
81   아파트1-102-404          436      2
62   아파트1-103-703          498      3

가구명  usage (kWh)  label
80  아파트1-103-1002          494      5