In [1]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [2]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import math as mt
import warnings

# 한글출력
matplotlib.rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False
warnings.filterwarnings(action='ignore') 

from src import crs, PublicPredictor
from src.dbc import utils, TimeDivisionKMeans

In [3]:
# 1. load_excel
data_path = "data/apt_1.xlsx"
xlsx = pd.read_excel(data_path, header=None,
                     skiprows=2, engine="openpyxl")

# 2. data preprocessing
p, m = crs.utils.data_preprocessing(xlsx)

m.set_index("month", inplace=True)

# 3. data init
_month = 1

month_df = pd.DataFrame(m.loc[_month])
month_df.reset_index(inplace=True)

month_df.columns = ['name', 'usage (kWh)']

PUBLIC_PERCENTAGE = 30
APT = crs.utils.get_APT(month_df, PUBLIC_PERCENTAGE)

calc = crs.models.ManagementOffice(
        month=_month,
        households=month_df,
        APT=APT,
        contract="단일계약"
    )
apt = calc.apart

In [4]:
m_15 = utils.data_preprocessing(xlsx)

df = utils.dimension_reduction(m_15)
m_60 = df.copy()

m_60.head()

m_60_1 = m_60[m_60.index.month == 1].copy()
m_60_1.head()

아파트1-104-1206  아파트1-104-303  아파트1-104-1307  \
2019-01-01 00:00:00          0.033         0.000          0.034   
2019-01-01 01:00:00          0.048         0.000          0.033   
2019-01-01 02:00:00          0.032         0.000          0.039   
2019-01-01 03:00:00          0.033         0.000          0.039   
2019-01-01 04:00:00          0.032         0.001          0.033   

                     아파트1-104-1208  아파트1-104-408  아파트1-104-203  아파트1-103-1402  \
2019-01-01 00:00:00          0.037         0.062         0.322          0.240   
2019-01-01 01:00:00          0.037         0.063         0.185          0.257   
2019-01-01 02:00:00          0.036         0.062         0.175          0.384   
2019-01-01 03:00:00          0.037         0.062         0.167          0.276   
2019-01-01 04:00:00          0.037         0.063         0.197          0.266   

                     아파트1-103-402  아파트1-103-1201  아파트1-103-801  ...  \
2019-01-01 00:00:00         0.295          0.373         0.243  ...   
2019-01-01 01:00:00         0.397          0.257         0.228  ...   
2019-01-01 02:00:00         0.353          0.123         0.141  ...   
2019-01-01 03:00:00         0.488          0.142         0.159  ...   
2019-01-01 04:00:00         0.278          0.190         0.227  ...   

                     아파트1-102-901  아파트1-103-1905  아파트1-103-503  아파트1-103-1504  \
2019-01-01 00:00:00         0.534          0.188         0.400          0.318   
2019-01-01 01:00:00         0.396          0.434         0.355          0.250   
2019-01-01 02:00:00         0.194          0.337         0.379          0.274   
2019-01-01 03:00:00         0.286          0.263         0.375          0.264   
2019-01-01 04:00:00         0.275          0.245         0.310          0.423   

                     아파트1-103-606  아파트1-103-903  아파트1-103-1106  아파트1-103-705  \
2019-01-01 00:00:00         0.420         0.626          0.484         0.289   
2019-01-01 01:00:00         0.465         0.409          0.459         0.336   
2019-01-01 02:00:00         0.326         0.307          0.405         0.382   
2019-01-01 03:00:00         0.336         0.345          0.298         0.291   
2019-01-01 04:00:00         0.360         0.364          0.212         0.347   

                     아파트1-103-1505  아파트1-103-406  
2019-01-01 00:00:00          0.305         0.652  
2019-01-01 01:00:00          0.332         0.557  
2019-01-01 02:00:00          0.311         0.491  
2019-01-01 03:00:00          0.261         0.511  
2019-01-01 04:00:00          0.294         0.507  

[5 rows x 108 columns]

In [5]:
from src import TimeDivisionKMeans

tdKMeans = TimeDivisionKMeans(datas=m_60_1)
tdKMeans.fit()

tdKMeans.cluster_info.head()[
    tdKMeans.cluster_info.columns[:10]
]

1/248 - ECV:85%
11/248 - ECV:78%
21/248 - ECV:86%
31/248 - ECV:88%
41/248 - ECV:86%
51/248 - ECV:82%
61/248 - ECV:88%
71/248 - ECV:85%
81/248 - ECV:88%
91/248 - ECV:83%
101/248 - ECV:86%
111/248 - ECV:82%
121/248 - ECV:88%
131/248 - ECV:77%
141/248 - ECV:85%
151/248 - ECV:88%
161/248 - ECV:88%
171/248 - ECV:79%
181/248 - ECV:82%
191/248 - ECV:82%
201/248 - ECV:88%
211/248 - ECV:80%
221/248 - ECV:84%
231/248 - ECV:80%
241/248 - ECV:87%
248/248 - ECV:86%


아파트1-104-1206 아파트1-104-303 아파트1-104-1307 아파트1-104-1208  \
division_round                                                          
0                          0            0             0             0   
1                          1            0             1             1   
2                          0            0             0             0   
3                          0            0             0             0   
4                          0            0             0             0   

               아파트1-104-408 아파트1-104-203 아파트1-103-1402 아파트1-103-402  \
division_round                                                        
0                         0            1             2            2   
1                         1            2             3            3   
2                         0            1             1            1   
3                         0            0             0            1   
4                         0            1             0            1   

               아파트1-103-1201 아파트1-103-801  
division_round                             
0                          1            1  
1                          2            2  
2                          1            1  
3                          1            0  
4                          1            1

In [6]:
tdKMeans.groups_

array([0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 2, 3, 1, 3, 2, 4, 2, 2, 2, 2, 3, 1,
       2, 3, 2, 2, 1, 2, 3, 2, 3, 2, 1, 1, 2, 3, 2, 2, 3, 2, 2, 2, 2, 3,
       2, 2, 3, 2, 2, 1, 2, 3, 3, 2, 2, 2, 1, 1, 2, 2, 3, 2, 4, 3, 3, 3,
       1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 4, 3, 2, 2, 3, 2, 3, 2,
       3, 3, 3, 2, 3, 2, 4, 2, 3, 3, 1, 2, 2, 2, 3, 2, 2, 2, 3, 2])

In [7]:
group_df = pd.DataFrame()

group_df['가구명'] = m_60_1.columns
group_df['usage (kWh)'] = m_60_1.sum().round().values.astype("int")
group_df['label'] = tdKMeans.groups_

group_df.head()

가구명  usage (kWh)  label
0  아파트1-104-1206           99      0
1   아파트1-104-303           10      0
2  아파트1-104-1307           23      0
3  아파트1-104-1208           40      0
4   아파트1-104-408           39      0

In [8]:
min_anomaly_data = pd.DataFrame()

for label in _unique_groups:
    now_step_df = group_df[group_df['label'] == label]
    next_step_min = group_df[group_df['label'] == (label + 1)]['usage (kWh)'].min()
    chk_idx = now_step_df['usage (kWh)'] > next_step_min
    chk = now_step_df[chk_idx]
    
    if len(chk) != 0:
        min_anomaly_data = min_anomaly_data.append(
            chk
        )
    
min_anomaly_data

NameError: name '_unique_groups' is not defined

# 최종 기여도그룹 부여 ( 1.라벨 )

In [279]:
labels_ = np.array([])

for col in tdKMeans.cluster_info.columns:
#     max_group = tdKMeans.cluster_info[col].value_counts().idxmax()
#     max_group = tdKMeans.cluster_info[col].mean().round().astype("int")
    counts = tdKMeans.cluster_info[col].value_counts()
    max_group = ((counts.index + 1) * counts).idxmax()
    
    
    labels_ = np.append(labels_,max_group)
    
labels_.astype("int")

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 2, 2, 6, 1, 1, 1, 1, 3, 0,
       1, 2, 1, 1, 0, 1, 2, 1, 2, 1, 1, 1, 1, 5, 1, 1, 4, 2, 2, 1, 1, 5,
       2, 1, 3, 1, 2, 1, 1, 3, 3, 1, 2, 1, 0, 1, 3, 6, 3, 1, 5, 2, 2, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 5, 2, 1, 1, 4, 2, 3, 2,
       2, 3, 1, 1, 2, 1, 6, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2])

In [364]:
labels_ = np.array([])

sum_datas = tdKMeans.datas.sum(axis=2).sum(axis=0)
sum_total = tdKMeans.datas.sum(axis=2).sum(axis=0).sum()

weights = sum_datas / sum_total

for col in tdKMeans.cluster_info.columns:
#     max_group = tdKMeans.cluster_info[col].value_counts().idxmax()
    max_group = round((tdKMeans.cluster_info[col] * weights).sum() / weights.sum())
    
    labels_ = np.append(labels_,max_group)
    
labels_.astype("int")

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 2, 2, 4, 1, 2, 1, 1, 3, 0,
       1, 2, 1, 1, 0, 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 2, 3, 1, 1, 1, 1, 2,
       1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 0, 1, 1, 2, 2, 1, 3, 2, 2, 2,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 0, 1, 3, 3, 1, 1, 3, 2, 3, 2,
       2, 3, 2, 2, 2, 2, 4, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2])

# 최종 기여도그룹 번호 부여

In [281]:
_unique_labels = np.unique(labels_)
groups_ = np.zeros(len(labels_)) - 1

for idx, label in enumerate(_unique_labels):
    groups_[labels_ == label] = idx
    
groups_

array([0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 2., 1., 2., 2., 6., 1.,
       1., 1., 1., 3., 0., 1., 2., 1., 1., 0., 1., 2., 1., 2., 1., 1., 1.,
       1., 5., 1., 1., 4., 2., 2., 1., 1., 5., 2., 1., 3., 1., 2., 1., 1.,
       3., 3., 1., 2., 1., 0., 1., 3., 6., 3., 1., 5., 2., 2., 1., 1., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 5., 2., 1., 1., 4.,
       2., 3., 2., 2., 3., 1., 1., 2., 1., 6., 1., 2., 2., 1., 1., 1., 1.,
       2., 1., 1., 1., 2., 2.])

# 최종 클러스터링 패턴 선정

In [386]:
# 0번 그룹 친구들
group_df = tdKMeans.cluster_info.iloc[:,tdKMeans.groups_ == 0]

In [387]:
_unique_groups = np.unique(tdKMeans.groups_)

In [388]:
clusters_ = np.array([])

for _group in _unique_groups:
    group_df = tdKMeans.cluster_info.iloc[:,tdKMeans.groups_ == _group]

    for _round in range(len(tdKMeans.kmeans_)):
        max_cluster = group_df.iloc[_round].value_counts().idxmax()

        clusters_ = np.append(
            clusters_,
            tdKMeans.kmeans_[_round].clusters_[max_cluster]
        )

print(clusters_.shape)
clusters_[:5]

(3720,)


array([0.092     , 0.05944444, 0.05611111, 0.1915    , 0.18011538])

In [389]:
clusters_ = clusters_.reshape(len(_unique_groups), -1)
clusters_

array([[0.092     , 0.05944444, 0.05611111, ..., 0.2248125 , 0.21275   ,
        0.20725   ],
       [0.25946512, 0.26255814, 0.25737209, ..., 0.49497959, 0.4767551 ,
        0.42371429],
       [0.4661875 , 0.3938125 , 0.3219375 , ..., 0.49497959, 0.4767551 ,
        0.42371429],
       [0.73991667, 0.66691667, 0.57533333, ..., 0.70086364, 0.83281818,
        0.73222727],
       [0.73991667, 0.66691667, 0.57533333, ..., 1.594     , 1.719     ,
        1.861     ]])

In [390]:
cluster_df = pd.DataFrame(clusters_.T, index=m_60_1.index)

cluster_df

0         1         2         3         4
2019-01-01 00:00:00  0.092000  0.259465  0.466187  0.739917  0.739917
2019-01-01 01:00:00  0.059444  0.262558  0.393813  0.666917  0.666917
2019-01-01 02:00:00  0.056111  0.257372  0.321938  0.575333  0.575333
2019-01-01 03:00:00  0.191500  0.191500  0.276767  0.593571  0.593571
2019-01-01 04:00:00  0.180115  0.180115  0.287167  0.637286  0.637286
...                       ...       ...       ...       ...       ...
2019-01-31 19:00:00  0.184000  0.415000  0.686909  0.778273  0.468000
2019-01-31 20:00:00  0.189348  0.411227  0.617636  0.712364  1.582000
2019-01-31 21:00:00  0.224813  0.494980  0.494980  0.700864  1.594000
2019-01-31 22:00:00  0.212750  0.476755  0.476755  0.832818  1.719000
2019-01-31 23:00:00  0.207250  0.423714  0.423714  0.732227  1.861000

[744 rows x 5 columns]

In [391]:
cluster_df.sum()

0    119.354141
1    229.435919
2    314.505670
3    425.978554
4    702.178765
dtype: float64

가구명  usage (kWh)  label
0  아파트1-104-1206           99      0
1   아파트1-104-303           10      0
2  아파트1-104-1307           23      0
3  아파트1-104-1208           40      0
4   아파트1-104-408           39      0

In [396]:
group_df[73:83]

가구명  usage (kWh)  label
73   아파트1-104-606          180      0
74  아파트1-104-1006           20      0
75   아파트1-104-902          176      1
76   아파트1-104-204          220      1
77  아파트1-104-1207          308      1
78   아파트1-103-602          181      0
79  아파트1-103-1302          203      1
80  아파트1-103-1002          494      3
81   아파트1-102-404          436      3
82  아파트1-103-1102          264      1

In [375]:
counts = tdKMeans.cluster_info['아파트1-104-708'].value_counts()
counts

0    140
1     97
2      7
3      4
Name: 아파트1-104-708, dtype: int64

In [ ]:
counts = tdKMeans.cluster_info['아파트1-104-708'].value_counts()
counts

In [291]:
((counts.index + 1.25) * counts).idxmax()

0

In [359]:
sum_1 = tdKMeans.datas.sum(axis=2).sum(axis=0)
sum_total = tdKMeans.datas.sum(axis=2).sum(axis=0).sum()

weights = sum_1 / sum_total
weights

array([0.00379019, 0.00326419, 0.00375199, 0.00504067, 0.00462839,
       0.00477289, 0.00582897, 0.0050152 , 0.00357267, 0.00333274,
       0.00418226, 0.00360048, 0.00360836, 0.00401066, 0.00546628,
       0.00502549, 0.00363331, 0.00337335, 0.00419207, 0.00385777,
       0.00343798, 0.00388047, 0.00504076, 0.00492421, 0.00354357,
       0.00322731, 0.0040542 , 0.00373395, 0.00361836, 0.00390083,
       0.00515902, 0.00486057, 0.00353582, 0.0031604 , 0.00379691,
       0.00429175, 0.00394947, 0.00422095, 0.00563467, 0.00472659,
       0.003628  , 0.00314162, 0.00398677, 0.00416767, 0.00408584,
       0.00453116, 0.00559319, 0.00505202, 0.00357289, 0.00319609,
       0.00421599, 0.0036071 , 0.00326387, 0.003826  , 0.00542204,
       0.00517738, 0.00373607, 0.0032367 , 0.00409809, 0.00358411,
       0.0036289 , 0.00408548, 0.00553014, 0.00532651, 0.00379118,
       0.00337431, 0.00437268, 0.00366842, 0.00334338, 0.00401137,
       0.00516365, 0.00484263, 0.00363074, 0.0032057 , 0.00410

In [362]:
round((tdKMeans.cluster_info['아파트1-102-301'] * weights).sum() / weights.sum())

3

In [395]:
min_anomaly_data = pd.DataFrame()

for label in _unique_groups:
    now_step_df = group_df[group_df['label'] == label]
    next_step_min = group_df[group_df['label'] == (label + 1)]['usage (kWh)'].min()
    chk_idx = now_step_df['usage (kWh)'] > next_step_min\
    
    chk = now_step_df[chk_idx]
    
    if len(chk) != 0:
        min_anomaly_data = min_anomaly_data.append(
            chk
        )
    
min_anomaly_data

가구명  usage (kWh)  label
73    아파트1-104-606          180      0
78    아파트1-103-602          181      0
58   아파트1-103-1404          298      1
77   아파트1-104-1207          308      1
91    아파트1-101-803          310      1
101  아파트1-103-1504          300      1
52   아파트1-103-1803          420      2